### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by kronkite115** [echocat/puppet-redis#101]
manifests/server.pp:199 and 203
$::operatingsystemmajrelease is a string and may not be compared to an integer.  

templates/systemd/sentinel.service.erb:2
"sentinel_name" needs to be "@sentinel_name"

Redis 2.8.19 does not understand "cluster-require-full-coverage"

**Comment by michaeljoy** [comment]
Simple fix for the string comparison to integer is to use the built in versioncmp function : 
```
  # startup script
  case $::osfamily {
    'RedHat': {
      $service_file = "/usr/lib/systemd/system/redis-server_${redis_name}.service"
      if versioncmp($::operatingsystemmajrelease, '7') > 0 { $has_systemd = true }
    }
    'Debian': {
      $service_file = "/etc/systemd/system/redis-server_${redis_name}.service"
      if versioncmp($::operatingsystemmajrelease, '7') > 0 { $has_systemd = true }
    }
    default:  {
      $has_systemd = false
    }
  }
```

**Comment by michaeljoy** [comment]
I will add that using osfamily here in context of systemd is also incorrect, as Ubuntu <16.04 does 'not' have systemd out of the box.

$::lsbdistid or $::operatingsystem works better as we don't want to select systemd for Ubuntu 14.04 here

**Comment by michaeljoy** [comment]
Note versioncmp is = 0 when parameter is equivalent, and > 0 when version compared of host is greater than parameter.
```
  # startup script
  case $::operatingsystem {
    'RedHat': {
      $service_file = "/usr/lib/systemd/system/redis-server_${redis_name}.service"
      if versioncmp($::operatingsystemmajrelease, '7') > 0 { $has_systemd = true }
    }
    'Debian': {
      $service_file = "/etc/systemd/system/redis-server_${redis_name}.service"
      if versioncmp($::operatingsystemmajrelease, '8') > 0 { $has_systemd = true }
    }
    'Ubuntu': {
      $service_file = "/etc/systemd/system/redis-server_${redis_name}.service"
      if versioncmp($::operatingsystemmajrelease, '14.04') > 0 { $has_systemd = true }
    }
    default:  {
      $has_systemd = false
    }
  }
```

**Comment by dwerder** [comment]
Do you want to send a PR to develop branch?

**Comment by michaeljoy** [comment]
Done sir. https://github.com/echocat/puppet-redis/pull/108

**Comment by dwerder** [comment]
Further discussions in PR #108
