### ISSUE TITLE
Unit is not loaded properly: Bad message

### ISSUE THREAD

**Issue by vkurguzov1pt** [echocat/puppet-redis#135]
Hello, after installing I got the message like in the subject.
 Also 
```
systemctl status redis-server_master.service
● redis-server_master.service
   Loaded: error (Reason: Bad message)
   Active: inactive (dead)

Feb 21 16:02:55 vmredisuk1 systemd[1]: [/usr/lib/systemd/system/redis-server_master.service:19] Invalid section header '[ "$NETWORKING" = "no" ] && exit 0'
Feb 21 16:05:13 vmredisuk1 systemd[1]: [/usr/lib/systemd/system/redis-server_master.service:13] Assignment outside of section. Ignoring.
Feb 21 16:05:13 vmredisuk1 systemd[1]: [/usr/lib/systemd/system/redis-server_master.service:16] Assignment outside of section. Ignoring.
Feb 21 16:05:13 vmredisuk1 systemd[1]: [/usr/lib/systemd/system/redis-server_master.service:19] Invalid section header '[ "$NETWORKING" = "no" ] && exit 0'
Feb 21 16:07:21 vmredisuk1 systemd[1]: [/usr/lib/systemd/system/redis-server_master.service:13] Assignment outside of section. Ignoring.
Feb 21 16:07:21 vmredisuk1 systemd[1]: [/usr/lib/systemd/system/redis-server_master.service:16] Assignment outside of section. Ignoring.
Feb 21 16:07:21 vmredisuk1 systemd[1]: [/usr/lib/systemd/system/redis-server_master.service:19] Invalid section header '[ "$NETWORKING" = "no" ] && exit 0'
Feb 21 16:07:28 vmredisuk1 systemd[1]: [/usr/lib/systemd/system/redis-server_master.service:13] Assignment outside of section. Ignoring.
Feb 21 16:07:28 vmredisuk1 systemd[1]: [/usr/lib/systemd/system/redis-server_master.service:16] Assignment outside of section. Ignoring.
Feb 21 16:07:28 vmredisuk1 systemd[1]: [/usr/lib/systemd/system/redis-server_master.service:19] Invalid section header '[ "$NETWORKING" = "no" ] && exit 0'
```
I have CentOS Linux release 7.3.1611 and Puppet 3.8.7

**Comment by dwerder** [comment]
Can you paste you puppet configuration, please?

**Comment by dwerder** [comment]
It seams that the init.d file is copied to the systemd location. But i don't know why.

**Comment by vkurguzov1pt** [comment]
Sorry for the delayed response.

from site.pp it is only
```
node 'vmredisuk1' {
  hiera_include('classes')
}
```

vim hieradata/nodes/vmredisuk1.profitero.local.yaml 
```
classes:
  - redis::install
redis::servers:
  'master':
    redis_memory        : '3g'
    redis_mempolicy     : 'no-eviction'
    redis_nr_dbs        : '16'
    redis_append_enable : true
    requirepass         : 'LaEwwWyZAf7s6QMLqn66Ae693tQsVuxpCDjyQ6au6CKzDmDHwxmBkmAgPJELFq3Q'
    enabled             : true
    redis_ip            : '0.0.0.0'
    redis_port          : '6379'
    redis_log_dir       : '/var/log/redis/'

```

**Comment by dwerder** [comment]
What are the puppet run logs saying? The config is fine. Which version of the module do u use?

**Comment by vkurguzov1pt** [comment]
I was using the latest 
```
[root@vmpuppet1 puppet]# puppet module list | grep redis
├── dwerder-redis (v2.1.0)
```
However when I downgrade to 1.9.0 everything works fine

**Comment by dwerder** [comment]
Ok, one small question. Can you send me the 'facter | grep -E "^o" '  output.
The only possible change between this version (1.9 vs 2.1) is the fact that we compare `operatingsystem` fact instead of `osfamily`

**Comment by vkurguzov1pt** [comment]
from node
sudo facter | grep -E "^o" 
```
operatingsystem => CentOS
operatingsystemmajrelease => 7
operatingsystemrelease => 7.4.1708
os => {"name"=>"CentOS", "family"=>"RedHat", "release"=>{"major"=>"7", "minor"=>"4", "full"=>"7.4.1708"}}
osfamily => RedHat
```

**Comment by jlmaners** [comment]
Don't know that this was every fully resolved in 2.1.x but I ran into this same issue today and reverting back to 1.9 fixed the issue for me as well.

**Comment by xshi0001** [comment]
Hi .I also got this bug,  install redis 5.0.9 / 2.1.x , same output of ' facter | grep -E "^o"' as you

**Comment by xshi0001** [comment]
[root@16c32g-centos75-0003 src]# ./redis-server /var/run/redis/redis_cluster-instance.conf , that can run ,it means I can't use systemd to manager redis service


and another bug is that: in templates\etc\redis.conf.erb



# cluster-require-full-coverage yes
<% if @cluster_require_full_coverage -%>cluster-require-full-coverage yes<% else -%>no<% end -%>


maybe:

# cluster-require-full-coverage yes
<% if @cluster_require_full_coverage -%>cluster-require-full-coverage yes<% else -%>cluster-require-full-coverage no<% end -%>
