### ISSUE TITLE
Add support for yum options

### ISSUE THREAD

**Issue by rmacduff** [echocat/puppet-redis#19]
Hello,

I'm getting the redis rpm from the remi repo which is disabled by default.  In order to install from this repo yum needs the additional option `--enablerepo=remi`.  I've created a branch that allows yum options to be passed in via a class parameter for such a situation.  If you think this would be a good option I can create a PR. 

https://github.com/rmacduff/puppet-redis/tree/add_yum_options

BTW, by far this is the best redis module out there!  It's made installing and configuring redis for my testing really easy.

-Ross

**Comment by dwerder** [comment]
Thanks man. But the configuration of a YUM repo should be handled by a yum module or your environment instead of this module.

You can realize that for example like:

```puppet

Package {install_options => '--enablerepo=remi' }
class redis {'bla': blub ... }
```

```

**Comment by rmacduff** [comment]
Yeah, in hindsight I can see that doing this sort of repo management inside of this module doesn't  make sense.  Thanks for the feedback.
