### ISSUE TITLE
with custom instance but default one keeps running

### ISSUE THREAD

**Issue by daks** [echocat/puppet-redis#24]
Hello,

I try to use your Puppet module on Debian 7 running Puppet 3.4. My tests use Vagrant.
I want to use the Debian packaged Redis version, and to configure my redis server to listen to all IPs, so I use the following code:

    class { 'redis::install':
        redis_version   => '2:2.8.17-1~bpo70+1+b1',
        redis_package   => true,
    }
    redis::server {
        'master':
            redis_ip    => '0.0.0.0',
            redis_port  => 6400,
            running     => true,
            enabled     => true,
    }

I thought the init.d file for the default server (/etc/init.d/redis-server) would be remove which is not the case, and in fact in my machine only the default redis server is running not my configured instance

    # netstat -utpln
    Proto Recv-Q Send-Q Adresse locale          Adresse distante        Etat        PID/Program name
    tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      2080/redis-server 1

I changed the port to 6400 to see if 2 instances will run, but it's not the case, even if I have 2 init files (one redis-server, one redis-server_master)

If I try to launch /etc/init.d/redis-server_master it won't work. If I stop the default one, I can start it.

I may have missed something in the documentation and my code may be wrong somewhere.
Could you tell me how I can:
- not have the default server run, maybe even not have its init file?
- have my configured one runs, and be 'monitored' by Puppet?

Thanks.

**Comment by dwerder** [comment]
Ok, thats a mistake in the configuration. If you use a repo package to install redis , then you can not configure the redis with that module.

The redis configuration only works, if the redis is install from source. The possibility to install redis RPMs/DEBs was implemented for people, who just want to install redis.

As a workaround, you can set `redis_install_dir` to the directory of the redis binary (`/bin` or `/usr/bin`) and remove the original init script.

**Comment by dwerder** [comment]
I have not much time at the moment, but maybe in the future the module should be aware if a repo package is used and configures everything correctly.

**Comment by daks** [comment]
Thanks for your answer. Maybe the documentation could be updated to indicate this restriction.
