### ISSUE TITLE
automatically include curl dependency

### ISSUE THREAD

**Issue by mcandre** [echocat/puppet-redis#25]
Include curl as an implicit dependency so that puppet users don't have to remember to install it.

**Comment by dwerder** [comment]
With the parameter `download_tool` in class `redis::install` you can change the it from curl to wget, or whatever fits your distrubution.

The default is 
```puppet
class { 'redis::install':
    download_tool => 'curl -s -L'
}
```

But you can also set it to:
```puppet
class { 'redis::install':
    download_tool => wget -qO-'
}
```

**Comment by mcandre** [comment]
Thanks, dwerder, that's a neat option.

In the event the download_tool is not specified, could the module automatically install the default download tool?
