### ISSUE TITLE
Dependency Failures

### ISSUE THREAD

**Issue by steverecio** [echocat/puppet-redis#28]
Provisioning gives several dependency errors despite having stdlib 4.6.0 installed. Shouldn't these be automatically installed by the puppet module?

Installation:

puppet module install --force --target-dir /usr/share/puppet/modules dwerder/redis

Puppet declaration:

class { 'redis::install':
          redis_version     => '3.0.2',
    }

Errors:

==> dev: Warning: /Stage[main]/Redis::Install/Anchor[redis::prepare_build]: Skipping because of failed dependencies
==> dev: Warning: /Stage[main]/Redis::Install/Exec[redis::compile]: Skipping because of failed dependencies
==> dev: Warning: /Stage[main]/Redis::Install/File[/opt/redis]: Skipping because of failed dependencies
==> dev: Warning: /Stage[main]/Redis::Install/Anchor[redis::install]: Skipping because of failed dependencies
==> dev: Warning: /Stage[main]/Redis::Install/Redis::Installbinary[redis-cli]/File[/usr/bin/redis-cli]: Skipping because of failed dependencies
==> dev: Warning: /Stage[main]/Redis::Install/Redis::Installbinary[redis-check-aof]/File[/usr/bin/redis-check-aof]: Skipping because of failed dependencies
==> dev: Warning: /Stage[main]/Redis::Install/Redis::Installbinary[redis-sentinel]/File[/usr/bin/redis-sentinel]: Skipping because of failed dependencies
==> dev: Warning: /Stage[main]/Redis::Install/Redis::Installbinary[redis-server]/File[/usr/bin/redis-server]: Skipping because of failed dependencies
==> dev: Warning: /Stage[main]/Redis::Install/Redis::Installbinary[redis-check-dump]/File[/usr/bin/redis-check-dump]: Skipping because of failed dependencies
==> dev: Warning: /Stage[main]/Redis::Install/Redis::Installbinary[redis-benchmark]/File[/usr/bin/redis-benchmark]: Skipping because of failed dependencies

**Comment by dwerder** [comment]
It should, but you used `--force` which ignores dependencies during installation.

**Comment by steverecio** [comment]
--force did not fix the issue but installing curl was the magic bullet :)
