### ISSUE TITLE
Server Not Starting

### ISSUE THREAD

**Issue by steverecio** [echocat/puppet-redis#29]
The puppet module is properly installing redis on my box but the redis::server configuration isn't getting set anywhere and the server isn't starting up. Is there something wrong with my configuration below? I'd prefer not to have to set init.d and conf files through puppet if this module can handle that setup for me.

    node 'redis.my.server' {
         class { 'redis::install':
               redis_version => '2.8.8',
         }

         redis::server {
            'master':
                redis_name      => 'master',
                redis_memory    => '1g',
                redis_ip        => '0.0.0.0',
                redis_port      => 6379,
                running         => true,
                enabled         => true,
         }
    }

**Comment by dwerder** [comment]
The config looks fine. Can you see something in the puppet logs/output?
And another hint: Use Redis 2.8.21 or 3.0.2. The default redis version is pretty old ;-)

If the puppet installation is succesfull, you should find an init script `/etc/init.d/redis-server_master` and a config file `/etc/redis_master.conf`

If you can not find something in the puppet output, try start the service manually `service redis-server_master start` and see if this gives some information.

**Comment by steverecio** [comment]
I updated the redis version to 3.0.2 but still nothing. When I provision, this is the only redis output:

```
devbox: $ vagrant provision dev | grep redis
==> dev: install redis
==> dev: └── dwerder-redis (v1.6.0)
```

The /etc files are never generated and `service redis-server_master start` returns as an unrecognized service, which makes sense given that there is no /etc/init.d/redis-server file generated. 

```
vagrant@precise64:~$ sudo find /etc/ -name "*redis*"
vagrant@precise64:~$
```

I never see any puppet output information regarding the redis server itself and it seems like the puppet redis::server configuration block never runs (even though redis itself gets installed within the same scope).

If it helps at all, I'm running all of this on ubuntu 12.04 with puppet 3.7.5.

**Comment by dwerder** [comment]
I dont work with vagrant, so i can not tell you exactly how to get the puppet run output. Maybe you can see something in /var/logs/syslog or so. Without any logging it very hard to tell whats going wrong.

**Comment by steverecio** [comment]
Sorry issue was I had to removed the enclosing ```node``` block.

Another question, is there a built-in parameter for configuring the running user? The redis-server process gets started properly but its run as root which concerns me from a security standpoint.

**Comment by dwerder** [comment]
At the moment the redis is running as root. There is no parameter to set the user. If someone provides a patch or pull request , then i will merge it.
