### ISSUE TITLE
Sentinel configuration issues

### ISSUE THREAD

**Issue by appcara-kaminglau** [echocat/puppet-redis#31]
Two issues spot here:

1.)  The sentinel config template "templates/etc/sentinel.conf.erb" should refer to the monitor variables as follow:
  @monitors.sort.each do |name, rule| %>

2.) In the case of using sentinel, then the redis config file should allow sentinel to manage:
  File["/etc/redis_${redis_name}.conf"] { replace => false, }

**Comment by dwerder** [comment]
First point is adressed.
Second point: take a look at parameter `force_rewrite`

**Comment by appcara-kaminglau** [comment]
The force_rewrite seems only address sentinel conf.  From what I understand sentinel will also try to rewrite the redis.conf (along with sentinel.conf) in the case of failover.  Correct me if I'm wrong.

**Comment by dwerder** [comment]
You are right. I added the parameter for redis server too.
