### ISSUE TITLE
Compile Error - Validation of Exec[Make dir /opt] failed

### ISSUE THREAD

**Issue by davpx** [echocat/puppet-redis#36]
Getting the following on it { should compile } in my tests

Failure/Error: it { should compile }
       error during compilation: Validation of Exec[Make dir /opt] failed: 'mkdir -p /opt' is not qualified and no path was specified. Please qualify the command or specify a path.

I also had to specifically call in 'epel-release' in order to get it to do anything, should this be installed by your module?

```ruby
class { '::redis::install':
    redis_version     => $redis_version,
    redis_build_dir   => '/opt',
    redis_install_dir => '/usr/bin',
    require           => Package['epel-release'],
  }
```

Any suggestions?

**Comment by dwerder** [comment]
The  `Exec[Make dir /opt]` take the global puppet puppet path variable `$::path` as default. If that variable is empty, then you get the path error. Normally it should not be empty ;)
But I dont how your puppet environment setup.

This module just installs required package, which should all be available from your distributions default repos. 

```
ensure_packages(['make', 'gcc', 'glibc-devel'], 
```
So you should not require epel. At least not, if you have the default RH/CentOS repos.
