### ISSUE TITLE
Systemd (Debian Jessie) not starting instances automatically

### ISSUE THREAD

**Issue by sebastianberm** [echocat/puppet-redis#38]
I've got: 
        redis::server {
                'ta-app':
                        redis_memory => '2g',
                        redis_ip => '10.130.46.184',
                        redis_port => '6379',
                        redis_mempolicy => 'allkeys-lru',
                        redis_timeout => 0,
                        redis_nr_dbs => 16,
                        redis_loglevel => 'notice',
                        running => true,
                        enabled => true,
    ....

This should start, however, it doesn't, when running the agent with debugging enabled:
Debug: Executing '/usr/sbin/service redis-server_ta-app start'
Error: Could not start Service[redis-server_ta-app]: Execution of '/usr/sbin/service redis-server_ta-app start' returned 6: Failed to start redis-server_ta-app.service: Unit redis-server_ta-app.service failed to load: No such file or directory.
Wrapped exception:
Execution of '/usr/sbin/service redis-server_ta-app start' returned 6: Failed to start redis-server_ta-app.service: Unit redis-server_ta-app.service failed to load: No such file or directory.
Error: /Stage[main]/Main/Node[ta-application-01]/Redis::Server[ta-app]/Service[redis-server_ta-app]/ensure: change from stopped to running failed: Could not start Service[redis-server_ta-app]: Execution of '/usr/sbin/service redis-server_ta-app start' returned 6: Failed to start redis-server_ta-app.service: Unit redis-server_ta-app.service failed to load: No such file or directory.
Debug: Executing '/usr/sbin/service redis-server_ta-app status'

This could be solved by letting the systemctl do an enable command when first installing / preparing:
>  systemctl enable redis-server_ta-app
Synchronizing state for redis-server_ta-app.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d redis-server_ta-app defaults
insserv: warning: script 'redis-server_ta-app' missing LSB tags and overrides
Executing /usr/sbin/update-rc.d redis-server_ta-app enable
update-rc.d: error: redis-server_ta-app Default-Start contains no runlevels, aborting.

> /etc/init.d/redis-server_ta-app start
[ ok ] Starting redis-server_ta-app (via systemctl): redis-server_ta-app.service.

Would it be possible to update this?

**Comment by dwerder** [comment]
Pull requests are welcome ;-)

**Comment by sebastianberm** [comment]
I know... 
But I don't fully trust myself with Puppet yet, so if this stays open long enough I'll do it, but otherwise, it might be simpler.

**Comment by dwerder** [comment]
The problem is, that this module has no real support for systemd. All configs are made for init.d.
I dont work with Debian distros. If you can provide a path or any other person who reads that. Send it.

**Comment by ayashjorden** [comment]
Hi @dwerder ,
I've pushed a new PR against `develop` branch.
Tested on Ubuntu Wily 15.10.

**Comment by dwerder** [comment]
More discussed in PR #61  and #62
