### ISSUE TITLE
Update-rc.d fails on Debian Squeeze with munin-node package installed

### ISSUE THREAD

**Issue by martinseener** [echocat/puppet-redis#72]
Hi,

we encountered an issue today while having munin-node package installed on Debian Squeeze. The Problem is, that update-rc.d fins a loop and stops adding the redis sysvinit scripts. The Issue looks like this:
> err: /Stage[main]//Node[redisserver]/Redis::Server[production]/Service[redis-server_production]/enable: change from false to true failed: Execution of '/usr/sbin/update-rc.d redis-server_production defaults' returned 1: update-rc.d: using dependency based boot sequencing
insserv: warning: script 'redis-server_production' missing LSB tags and overrides
insserv: warning: script 'redis-server_staging' missing LSB tags and overrides
insserv: There is a loop between service munin-node and redis-server_production if stopped
insserv:  loop involving service redis-server_production at depth 2
insserv:  loop involving service munin-node at depth 1
insserv: Stopping redis-server_production depends on munin-node and therefore on system facility `$all' which can not be true!
insserv: Stopping redis-server_staging depends on munin-node and therefore on system facility `$all' which can not be true!
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header

I was able to fix this by adding a proper INIT INFO part at the begin of the init-script. You can see my manual fix here: https://github.com/martinseener/puppet-redis/blob/master/templates/etc/init.d/debian_redis-server.erb.

If you like this fix, i can create a PR for you. Otherwise add it yourself or just close this issue. The fix i made works perfectly by the way.

**Comment by dwerder** [comment]
Is this problem only related to Squeeze? Do you have another/newer Debian version to test it?
Because Squeeze is EOL since February 2016.

**Comment by martinseener** [comment]
Hi,

i haven't tested it on wheezy or jessie - yet. But i can do it later and report back if the problem persists. We had to fix it for squeeze because we still have it in place for some more weeks before we switch over to jessie (just writing everything for jessie in puppet which still needs some weeks)

**Comment by dwerder** [comment]
It would be great if you can test it on wheezy and/or jessie. If we have the same problem there, then I would accept the patch.

**Comment by martinseener** [comment]
Hi,
i've upgraded my Squeeze instance to Wheezy and used wheezy's munin init.d file which fixed the problem described above, so my fix is only necessary for Squeeze for Ubuntu with comparable version of munin using the $all system facility in the sysVinit script.

Therefore i'll close this issue but it's a good reference for people with the same problem. Thank you!
