### ISSUE TITLE
Failed to start on CentOS 7.2 after update to 1.8.0

### ISSUE THREAD

**Issue by bkibilko** [echocat/puppet-redis#73]
After updating module to 1.8.0 I can't run redis on my CentOS 7.2. It doesn't even create log files. The only thing I have is log from systemctl status:
`Apr 07 11:17:05 vagrant02.dev.pl systemd[1]: Failed to start Redis persistent key-value database server.`

The machine is created with Vagrant using box puppetlabs/centos-7.2-64-puppet

This is my redis.pp:
https://gist.github.com/bkibilko/9c7914195d9b1c28c8e0a191ed3b5133

... and variables from hiera:
https://gist.github.com/bkibilko/14986c03a7b88a2d78a35fe70b25006f

After downgrading to 1.7.0 it works fine.

**Comment by dwerder** [comment]
I fixed some issues with the systemd scripts, which were really buggy. It should work with the develop branch now.

**Comment by dwerder** [comment]
release 1.8.1 should fix that issue

**Comment by bkibilko** [comment]
:+1:
