### ISSUE TITLE
redis-check-dump was renamed to redis-check-rdb in redis version 3.2

### ISSUE THREAD

**Issue by bkibilko** [echocat/puppet-redis#75]
There is new version of redis which causes the module to fail on installation:

`Error: /Stage[main]/Redis::Install/Redis::Installbinary[redis-check-dump]/File[/usr/bin/redis-check-dump]: Could not evaluate: Could not retrieve information from environment vagrant source(s) file:/opt/redis/redis-check-dump`

**Comment by alejandrodnm** [comment]
I'm having the same problem in a Centos 7.1 machine

**Comment by dwerder** [comment]
The redis-check-dump command was renamed to redis-check-rdb in redis 3.2

**Comment by dwerder** [comment]
Fixed in  734defe on develop branch
