### ISSUE TITLE
redis-check-dump doesn't exists in redis 3.2

### ISSUE THREAD

**Issue by bradziszewski** [echocat/puppet-redis#78]
looks like redis-check-dump should be option:
`Error: /Stage[main]/Redis::Install/Redis::Installbinary[redis-check-dump]/File[/usr/bin/redis-check-dump]: Could not evaluate: Could not retrieve information from environment production source(s) file:/opt/redis/redis/redis-check-dump`

**Comment by dwerder** [comment]
This is already fixed in the develop branch

**Comment by bradziszewski** [comment]
thanks

**Comment by dwerder** [comment]
There will be a new release 1.8.2 in the next hours
