### ISSUE TITLE
Systemctl unable to start redis-server: Can't open the log file: Permission denied

### ISSUE THREAD

**Issue by alecswan** [echocat/puppet-redis#91]
Hi there,

I am using 1.9.0 version of this puppet-redis module to install and start Redis 3.2.3 server on CentOS 7 with puppet 3.8.7. The error shown below is logged to journalctl when puppet tries to start redis-server via systemd as root user (service config is shown at the bottom). I do not get any errors and redis-server starts up fine when I run `/usr/bin/redis-server /var/run/redis/redis_redis1.conf --daemonize no` as root.

Similar issues have been reported by [others](https://github.com/gplessis/dotdeb-redis/issues/7).

Any ideas on how to fix this?

```
systemd[1]: Starting Redis redis_redis1 database server...
systemd[1]: Started Redis redis_redis1 database server.
redis-server[30824]: *** FATAL CONFIG FILE ERROR ***
redis-server[30824]: Reading the configuration file, at line 52
redis-server[30824]: >>> 'logfile /var/log/redis/redis_redis1.log'
redis-server[30824]: Can't open the log file: Permission denied
systemd[1]: redis-server_redis1.service: main process exited, code=exited, status=1/FAILURE
```

```
>> cat /usr/lib/systemd/system/redis-server_redis1.service
[Unit]
Description=Redis redis_redis1 database server
After=network.target

[Service]
ExecStartPre=/bin/mkdir -p /var/run/redis
ExecStartPre=/bin/cp -u /etc/redis_redis1.conf /var/run/redis/redis_redis1.conf
ExecStart=/usr/bin/redis-server /var/run/redis/redis_redis1.conf --daemonize no
ExecStop=/usr/bin/redis-cli -p 6800 shutdown
User=root
Group=root

[Install]
WantedBy=multi-user.target
```

```
ls -lah /var/log/redis/redis_redis1.log
-rw-rw-r--. 1 redis redis 51K Sep 25 01:27 /var/log/redis/redis_redis1.log
```

**Comment by alecswan** [comment]
I ended up disabling selinux as a workaround which is not ideal.

**Comment by ethompsy** [comment]
@alecswan This might help:
https://serverfault.com/questions/816052/unable-to-start-redis-under-selinux
