### ISSUE TITLE
Add support to run redis server instances under non-root user

### ISSUE THREAD

**Issue by btlogy** [echocat/puppet-redis#93]
As discussed in #29, proper support for non-root user should also (help to) fix #91 and #92.

**Comment by btlogy** [comment]
I've submit pull-request #94 to add this feature for CentOS 6 at least. I can not tell for sure it will work on Redhat 6, but it could well be the case.
I'll see later to bring the same feature for CentOS 7 and see the Sentinel manifest and template do not require the same improvement.
I just don't have time right now.
But I'll unlikely work on the other distros. Sorry.

**Comment by dwerder** [comment]
Closed because of age.
