### ISSUE TITLE
Debian 8 is using systemd by default, this module doesn't act accordingly

### ISSUE THREAD

**Issue by Kyoshiro-san** [echocat/puppet-redis#98]
Hi,

I'm using Debian jessie with default init (systemd) and the module fails to start the service because it is not creating the service file.

Here's a patch, although it is not checking if systemd is currently in use. This might need a new fact as I couldn't find one.
[20161104-puppet-redis-systemd-fix.diff.txt](https://github.com/echocat/puppet-redis/files/572047/20161104-puppet-redis-systemd-fix.diff.txt)

Best regards
Loïc

**Comment by dwerder** [comment]
closed by f29acea
